# Generated by Django 2.2.6 on 2019-12-17 12:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_afiliado', models.CharField(max_length=45, unique=True, verbose_name='Número de Afiliado')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefono')),
                ('dni', models.CharField(blank=True, max_length=45, null=True, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'agente',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
