# Generated by Django 2.2.6 on 2020-01-21 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id_afiliado', models.AutoField(primary_key=True, serialize=False)),
                ('num_afiliado', models.CharField(max_length=45, unique=True, verbose_name='Número de Afiliado')),
                ('num_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefono')),
                ('dni', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='DNI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'db_table': 'afiliado',
                'managed': True,
            },
        ),
    ]
