# Generated by Django 2.2.6 on 2019-12-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='afiliado',
            table='afiliado',
        ),
    ]
