# Generated by Django 2.2.6 on 2020-06-24 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de afuliado debe ser ingresado en formato: 99999/9 o 99999. Hasta 7 caracteres son permitidos', regex='(?:(\\d{5})([/]\\d{1})?)'), django.core.validators.MinLengthValidator(7)], verbose_name='DNI'),
        ),
    ]
