# Generated by Django 2.2.6 on 2020-06-29 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200624_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_tel',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='El número de telefono debe ser ingresado sin 0 y 15, no se permiten letras. Hasta 10 digitos permitidos', regex='^(?:\\(?\\d{2,3}\\)?[- .]?\\d{4,5}[- .]?\\(?\\d{4}\\)?)'), django.core.validators.MinLengthValidator(10)], verbose_name='Número de Telefono'),
        ),
    ]
