# Generated by Django 2.2.6 on 2019-11-15 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('num_afiliado', models.CharField(max_length=45, verbose_name='Número de Afiliado')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField()),
                ('num_tel', models.CharField(max_length=11, verbose_name='Número de Telefono')),
                ('email', models.CharField(max_length=45)),
                ('dni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'agente',
                'ordering': ['apellido', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['ciudad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('num_comision', models.IntegerField(verbose_name='Número de Comisión')),
                ('fech_inicio', models.DateField()),
                ('fech_fin', models.DateField()),
                ('gasto', models.FloatField()),
            ],
            options={
                'verbose_name': 'Comision',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'comision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleTrabajo',
            fields=[
                ('id_det_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('km_salida', models.IntegerField()),
                ('km_llegada', models.IntegerField()),
                ('detalle_trabajo', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'detalle_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itineraio',
            fields=[
                ('id_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('salida', models.CharField(max_length=45)),
                ('llegada', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detalle_recorrido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('num_legajo', models.CharField(max_length=45, verbose_name='Numero de Legajo')),
                ('patente', models.CharField(max_length=45, verbose_name='Patente')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
