# Generated by Django 2.2.6 on 2019-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('num_tel', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'agente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('fech_inicio', models.DateField()),
                ('fech_fin', models.DateField()),
                ('gasto', models.FloatField()),
            ],
            options={
                'db_table': 'comision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleRecorrido',
            fields=[
                ('id_det_recorrido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('salida', models.CharField(max_length=45)),
                ('llegada', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detalle_recorrido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleTrabajo',
            fields=[
                ('id_det_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('km_salida', models.IntegerField()),
                ('km_llegada', models.IntegerField()),
                ('detalle_trabajo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'detalle_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('num_legajo', models.CharField(max_length=45)),
                ('patente', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
