# Generated by Django 2.2.6 on 2020-01-21 18:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTrabajo',
            fields=[
                ('id_det_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('km_salida', models.IntegerField()),
                ('km_llegada', models.IntegerField()),
                ('detalle_trabajo', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'detalle_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['ciudad'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('num_comision', models.CharField(max_length=45, unique=True, verbose_name='Número de Comisión')),
                ('fech_inicio', models.DateField()),
                ('fech_fin', models.DateField()),
                ('gastos', models.FloatField()),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Ciudad')),
            ],
            options={
                'verbose_name': 'Comision',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'comision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('num_legajo', models.CharField(max_length=45, unique=True, verbose_name='Numero de Legajo')),
                ('patente', models.CharField(max_length=45, verbose_name='Patente')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitud_x_Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_registro', models.DateField(auto_now_add=True)),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Comision')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud por Afiliado',
                'verbose_name_plural': 'Solicitudes por Afiliados',
                'db_table': 'solicitud_x_afiliado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Comision',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('fech_inicio', models.DateField()),
                ('gastos_previsto', models.FloatField()),
                ('motivo', ckeditor.fields.RichTextField()),
                ('duracion_prevista', models.CharField(max_length=20)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Ciudad')),
                ('id_transporte', models.ForeignKey(db_column='id_transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Transporte')),
            ],
            options={
                'verbose_name': 'Solicitud de Comisón',
                'verbose_name_plural': 'Solicitudes de Comisiones',
                'db_table': 'solicitud_comision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itineraio',
            fields=[
                ('id_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('salida', models.CharField(max_length=45)),
                ('llegada', models.CharField(max_length=45)),
                ('id_comision', models.ForeignKey(db_column='id_comision', on_delete=django.db.models.deletion.DO_NOTHING, to='comisionApp.Comision')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'db_table': 'itinerario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comision_x_Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_registro', models.DateField(auto_now_add=True)),
                ('id_afiliado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Afiliado')),
                ('id_comision', models.ForeignKey(db_column='id_comision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Comision')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comision por Afiliado',
                'verbose_name_plural': 'Comisiones por Afiliados',
                'db_table': 'comision_x_afiliado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='id_transporte',
            field=models.ForeignKey(db_column='id_transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Transporte'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.CASCADE, to='comisionApp.Provincia'),
        ),
    ]
