# Generated by Django 2.2.6 on 2019-11-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraio',
            options={'managed': False, 'verbose_name': 'Itinerario'},
        ),
    ]
