# Generated by Django 2.2.6 on 2019-10-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'managed': False, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False, 'ordering': ['ciudad'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='comision',
            options={'managed': False, 'verbose_name': 'Comision', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'managed': False, 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'managed': False, 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
    ]
