# Generated by Django 2.2.6 on 2020-02-17 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comision_x_afiliado',
            unique_together={('id_user', 'id_comision')},
        ),
    ]
