# Generated by Django 2.2.6 on 2020-01-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitud_comision',
            table='solicitud_comision',
        ),
    ]
