# Generated by Django 2.2.6 on 2019-12-17 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comisionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='id_usuario',
        ),
        migrations.CreateModel(
            name='Comision_x_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_registro', models.DateField()),
                ('id_comision', models.ForeignKey(db_column='id_comision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comisionApp.Comision')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comision por Afiliado',
                'verbose_name_plural': 'Comisiones por Afiliados',
                'db_table': 'comision_x_usuario',
                'managed': True,
            },
        ),
    ]
