# Generated by Django 2.2.6 on 2019-11-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0002_auto_20191025_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleRecorrido',
        ),
    ]
