# Generated by Django 2.2.6 on 2020-03-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0002_auto_20200318_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalletrabajo',
            options={'managed': True, 'verbose_name': 'Detalle de Trabajo'},
        ),
    ]
