# Generated by Django 2.2.6 on 2020-01-20 17:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0002_auto_20200120_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='solicitud_comision',
            name='motivo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
