# Generated by Django 2.2.6 on 2020-03-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0002_auto_20200325_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalletrabajo',
            old_name='rendicion',
            new_name='anticipo',
        ),
        migrations.RenameField(
            model_name='itineraio',
            old_name='rendicion',
            new_name='anticipo',
        ),
    ]
