# Generated by Django 2.2.6 on 2020-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0002_auto_20200406_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraio',
            name='dia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itineraio',
            name='mes',
            field=models.CharField(max_length=10),
        ),
    ]
