# Generated by Django 2.2.6 on 2020-06-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0003_auto_20200410_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='num_comision',
        ),
    ]
