# Generated by Django 2.2.6 on 2019-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0003_delete_detallerecorrido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecorrido',
            fields=[
                ('id_det_recorrido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('salida', models.CharField(max_length=45)),
                ('llegada', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detalle_recorrido',
                'managed': False,
            },
        ),
    ]
