# Generated by Django 2.2.6 on 2020-03-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0003_auto_20200318_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticipo',
            options={'managed': True, 'verbose_name': 'Anticipo', 'verbose_name_plural': 'Anticipos'},
        ),
        migrations.AlterModelOptions(
            name='integrantes_x_anticipo',
            options={'managed': True, 'verbose_name': 'Integrantes de anticipo', 'verbose_name_plural': 'Integrantes por anticipo'},
        ),
        migrations.AlterModelOptions(
            name='integrantes_x_solicitud',
            options={'managed': True, 'verbose_name': 'Integrantes de solicitud', 'verbose_name_plural': 'Integrantes por solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': True, 'verbose_name': 'Solicitud de Comisón', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
