# Generated by Django 2.2.6 on 2020-01-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('comisionApp', '0003_auto_20200120_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision_x_afiliado',
            name='id_afiliado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Afiliado'),
        ),
    ]
