# Generated by Django 2.2.6 on 2020-07-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0004_remove_anticipo_num_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes_x_anticipo',
            name='anticipo',
            field=models.ForeignKey(db_column='id_anticipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='comisionApp.Anticipo'),
        ),
    ]
