# Generated by Django 2.2.6 on 2020-07-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisionApp', '0005_auto_20200701_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletrabajo',
            name='anticipo',
            field=models.ForeignKey(db_column='id_anticipo', on_delete=django.db.models.deletion.CASCADE, to='comisionApp.Anticipo'),
        ),
        migrations.AlterField(
            model_name='itineraio',
            name='anticipo',
            field=models.ForeignKey(db_column='id_anticipo', on_delete=django.db.models.deletion.CASCADE, to='comisionApp.Anticipo'),
        ),
    ]
